/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerRouteImport } from './routes/_player'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as GameRouteImport } from './routes/game'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResultRouteImport } from './routes/result'
import { Route as WaitingRoomRouteImport } from './routes/waiting-room'
import { Route as PlayerDashboardRouteImport } from './routes/_player.dashboard'
import { Route as PlayerHistoryRouteImport } from './routes/_player.history'
import { Route as PlayerPracticeBattleRouteImport } from './routes/_player.practice-battle'
import { Route as PlayerProfileRouteImport } from './routes/_player.profile'
import { Route as PlayerReferralRouteImport } from './routes/_player.referral'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'
import { Route as AdminReferralRouteImport } from './routes/admin.referral'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as PlayerWalletIndexRouteImport } from './routes/_player.wallet.index'
import { Route as PlayerWalletDepositRouteImport } from './routes/_player.wallet.deposit'
import { Route as PlayerWalletWithdrawRouteImport } from './routes/_player.wallet.withdraw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/_player',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingRoomRoute = WaitingRoomRouteImport.update({
  id: '/waiting-room',
  path: '/waiting-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerDashboardRoute = PlayerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerHistoryRoute = PlayerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerPracticeBattleRoute = PlayerPracticeBattleRouteImport.update({
  id: '/practice-battle',
  path: '/practice-battle',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerProfileRoute = PlayerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerReferralRoute = PlayerReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => PlayerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReferralRoute = AdminReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const PlayerWalletIndexRoute = PlayerWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerWalletDepositRoute = PlayerWalletDepositRouteImport.update({
  id: '/wallet/deposit',
  path: '/wallet/deposit',
  getParentRoute: () => PlayerRoute,
} as any)
const PlayerWalletWithdrawRoute = PlayerWalletWithdrawRouteImport.update({
  id: '/wallet/withdraw',
  path: '/wallet/withdraw',
  getParentRoute: () => PlayerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/dashboard': typeof PlayerDashboardRoute
  '/history': typeof PlayerHistoryRoute
  '/practice-battle': typeof PlayerPracticeBattleRoute
  '/profile': typeof PlayerProfileRoute
  '/referral': typeof PlayerReferralRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/wallet/deposit': typeof PlayerWalletDepositRoute
  '/wallet/withdraw': typeof PlayerWalletWithdrawRoute
  '/wallet/': typeof PlayerWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/dashboard': typeof PlayerDashboardRoute
  '/history': typeof PlayerHistoryRoute
  '/practice-battle': typeof PlayerPracticeBattleRoute
  '/profile': typeof PlayerProfileRoute
  '/referral': typeof PlayerReferralRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin': typeof AdminIndexRoute
  '/wallet/deposit': typeof PlayerWalletDepositRoute
  '/wallet/withdraw': typeof PlayerWalletWithdrawRoute
  '/wallet': typeof PlayerWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_player': typeof PlayerRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/game': typeof GameRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/waiting-room': typeof WaitingRoomRoute
  '/_player/dashboard': typeof PlayerDashboardRoute
  '/_player/history': typeof PlayerHistoryRoute
  '/_player/practice-battle': typeof PlayerPracticeBattleRoute
  '/_player/profile': typeof PlayerProfileRoute
  '/_player/referral': typeof PlayerReferralRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/referral': typeof AdminReferralRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/admin/': typeof AdminIndexRoute
  '/_player/wallet/deposit': typeof PlayerWalletDepositRoute
  '/_player/wallet/withdraw': typeof PlayerWalletWithdrawRoute
  '/_player/wallet/': typeof PlayerWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/game'
    | '/login'
    | '/register'
    | '/result'
    | '/waiting-room'
    | '/dashboard'
    | '/history'
    | '/practice-battle'
    | '/profile'
    | '/referral'
    | '/admin/deposits'
    | '/admin/matches'
    | '/admin/referral'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/admin/'
    | '/wallet/deposit'
    | '/wallet/withdraw'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game'
    | '/login'
    | '/register'
    | '/result'
    | '/waiting-room'
    | '/dashboard'
    | '/history'
    | '/practice-battle'
    | '/profile'
    | '/referral'
    | '/admin/deposits'
    | '/admin/matches'
    | '/admin/referral'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/admin'
    | '/wallet/deposit'
    | '/wallet/withdraw'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/_player'
    | '/admin'
    | '/game'
    | '/login'
    | '/register'
    | '/result'
    | '/waiting-room'
    | '/_player/dashboard'
    | '/_player/history'
    | '/_player/practice-battle'
    | '/_player/profile'
    | '/_player/referral'
    | '/admin/deposits'
    | '/admin/matches'
    | '/admin/referral'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/admin/'
    | '/_player/wallet/deposit'
    | '/_player/wallet/withdraw'
    | '/_player/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerRoute: typeof PlayerRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  GameRoute: typeof GameRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResultRoute: typeof ResultRoute
  WaitingRoomRoute: typeof WaitingRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_player': {
      id: '/_player'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-room': {
      id: '/waiting-room'
      path: '/waiting-room'
      fullPath: '/waiting-room'
      preLoaderRoute: typeof WaitingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_player/dashboard': {
      id: '/_player/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PlayerDashboardRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/history': {
      id: '/_player/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof PlayerHistoryRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/practice-battle': {
      id: '/_player/practice-battle'
      path: '/practice-battle'
      fullPath: '/practice-battle'
      preLoaderRoute: typeof PlayerPracticeBattleRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/profile': {
      id: '/_player/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PlayerProfileRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/referral': {
      id: '/_player/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof PlayerReferralRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referral': {
      id: '/admin/referral'
      path: '/referral'
      fullPath: '/admin/referral'
      preLoaderRoute: typeof AdminReferralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_player/wallet/': {
      id: '/_player/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof PlayerWalletIndexRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/wallet/deposit': {
      id: '/_player/wallet/deposit'
      path: '/wallet/deposit'
      fullPath: '/wallet/deposit'
      preLoaderRoute: typeof PlayerWalletDepositRouteImport
      parentRoute: typeof PlayerRoute
    }
    '/_player/wallet/withdraw': {
      id: '/_player/wallet/withdraw'
      path: '/wallet/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof PlayerWalletWithdrawRouteImport
      parentRoute: typeof PlayerRoute
    }
  }
}

interface PlayerRouteChildren {
  PlayerDashboardRoute: typeof PlayerDashboardRoute
  PlayerHistoryRoute: typeof PlayerHistoryRoute
  PlayerPracticeBattleRoute: typeof PlayerPracticeBattleRoute
  PlayerProfileRoute: typeof PlayerProfileRoute
  PlayerReferralRoute: typeof PlayerReferralRoute
  PlayerWalletDepositRoute: typeof PlayerWalletDepositRoute
  PlayerWalletWithdrawRoute: typeof PlayerWalletWithdrawRoute
  PlayerWalletIndexRoute: typeof PlayerWalletIndexRoute
}

const PlayerRouteChildren: PlayerRouteChildren = {
  PlayerDashboardRoute: PlayerDashboardRoute,
  PlayerHistoryRoute: PlayerHistoryRoute,
  PlayerPracticeBattleRoute: PlayerPracticeBattleRoute,
  PlayerProfileRoute: PlayerProfileRoute,
  PlayerReferralRoute: PlayerReferralRoute,
  PlayerWalletDepositRoute: PlayerWalletDepositRoute,
  PlayerWalletWithdrawRoute: PlayerWalletWithdrawRoute,
  PlayerWalletIndexRoute: PlayerWalletIndexRoute,
}

const PlayerRouteWithChildren =
  PlayerRoute._addFileChildren(PlayerRouteChildren)

interface AdminRouteChildren {
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminReferralRoute: typeof AdminReferralRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDepositsRoute: AdminDepositsRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminReferralRoute: AdminReferralRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerRoute: PlayerRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  GameRoute: GameRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResultRoute: ResultRoute,
  WaitingRoomRoute: WaitingRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
